spring:
  datasource:
    name: m1
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  application:
    name: USER-SERVICE
server:
  port: 8081

  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update   
    generate-ddl: true     
         
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka      


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
   
  endpoint:
     health:
        show-details: always
        
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        wait-duration-in-open-state:  6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
           
  retry:
   instances:
     ratingHotelService:
       max-attempts: 3
       wait-duration: 5s

          
    