server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
 
  application:
    name: VaccinationCenter-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost