server:
  port: 8989
  
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
        filters:
        - name: CircuitBreaker
          args:
             name: order-service
             fallbackuri: forword:/orderFallBack
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
        filters:
        - name: CircuitBreaker
          args:
             name: payment-service
             fallbackuri: forword:/paymentFallBack
      discovery:
        locator:
          enabled: true
     
          
        

    
  
   
management: 
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info, health
        
#Hystrix Configuration
hystrix:
  command: 
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


 
  