server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PAYMENT-SERVICE
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
 